<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Generated by GameMaker:Studio http://www.yoyogames.com/gamemaker/studio -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="pragma" content="no-cache"/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name ="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta charset="utf-8"/>

        <!-- Set the title bar of the page -->
        <title>Dice Score Keeper</title>

		<!-- Load Proper CSS Template File-->
        <script src="./Scripts/Load_CSS_Template.js"></script> 
		<script>Start(0);</script>
        <!-- Set the background colour of the document -->
	<style>
           body { 
              margin: 0px auto;
              padding: 0px;
              border: 0px;
            }
            canvas {
                      image-rendering: optimizeSpeed;
                      -webkit-interpolation-mode: nearest-neighbor;
                      -ms-touch-action: none;
                       margin: 0px;
                      padding: 0px;
                      border: 0px;
            }
            :-webkit-full-screen #canvas {
                 width: 100%;
                 height: 100%;
            }
            div.gm4html5_div_class
            {
				 margin: 0;
				 padding: 0px;
				 border: 0px;
            }
            /* START - Login Dialog Box */
            div.gm4html5_login
            {
                 padding: 20px;
                 position: absolute;
                 border: solid 2px #000000;
                 background-color: #404040;
                 color:#00ff00;
                 border-radius: 15px;
                 box-shadow: #101010 20px 20px 40px;
            }
            div.gm4html5_cancel_button
            {
                 float: right;
            }
            div.gm4html5_login_button
            {
                 float: left;
            }
            div.gm4html5_login_header
            {
                 text-align: center;
            }
            /* END - Login Dialog Box */
            :-webkit-full-screen {
               width: 100%;
               height: 100%;
            }
    	    #Title { 
                 margin: 0 auto;
				 width: 350px;
            }
        </style>
    </head>

    <body>
	<div id="Full_Screen_Wrapper" class="center">
	<?php include $_SERVER['DOCUMENT_ROOT'].'/Navigation.php'; ?>

	<div id="Title">
	    <h1>10,000 Dice Score Keeper</h1>
	</div>

        <div class="gm4html5_div_class" id="gm4html5_div_id">
            <!-- Create the canvas element the game draws to -->
            <canvas id="canvas" width="640" height="480">
               <p>Your browser doesn't support HTML5 canvas.</p>
            </canvas>
        </div>
		 <div id="Dice">
            <p><b>Description: </b>A simple application that will keep score for the classic game of Dice (10,000). I could never seem to find a pen and paper when I needed one so I created this app primarily for my Android phone.</p>                      
            <p><b>Download Android APK: </b><a href="Download_Files/Dice.apk" target="_blank">Dice Score Keeper zipped</a></p>                          
        </div>
        <!-- Run the game code -->
        <script type="text/javascript" src="Dice/dice.js?ZHGZB=1795660973"></script>
	</div><!-- End Wrapper -->
		<?php include $_SERVER['DOCUMENT_ROOT'].'/Footer.php'; ?>
    </body>
</html>
